name: 'Run tests'

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  formatting:
    name: 'Check Formatting using Black'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: 'Set up Python'
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: 'Install Formatting checkers'
      run: |
        python -m pip install --upgrade pip
        pip install black==22.3.0
    - name: 'Check Formatting using Black'
      run: |
        black --check .

  tests:
    name: 'Run tests and publish'
    runs-on: ubuntu-latest
    env:
      DISPLAY: ':99.0'
    steps:
    - uses: actions/checkout@v2
    - run: ./tools/setup_xvfb.sh
      name: 'Setup xvfb'   
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: 'Install dependencies'
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev]"
    - name: 'Run Pytest with xvfb'
      run: |
        pytest --cov=bfieldtools ./tests
        # Push coverage to codecov.io
        bash <(curl -s https://codecov.io/bash)
